# Array Modification

Getting started :-

In [188]:
import numpy as np

---> arrays are of fixed size, hence we have to modify array by making new array, ie orignal array remain same

In [189]:
arr_1d=np.array([1,2,3,4,5,6,7,8,9])
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_3d=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[11,22,33],[44,55,66],[77,88,99]]])

print(arr_1d ,"\n\n\n")
print(arr_2d, "\n\n\n\n\n")
print(arr_3d, "\n\n\n")

[1 2 3 4 5 6 7 8 9] 



[[1 2 3]
 [4 5 6]
 [7 8 9]] 





[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 22 33]
  [44 55 66]
  [77 88 99]]] 





## 1. Insert - np.insert(array, index, value, axis=NONE)

##### 1. In 1d array====> axis=0 default

##### 2. In 2d array====> axis=0 ----> insert in row
##### 2. In 2d array====> axis=1 ----> insert in column


##### 3. In 3d array====> axis=0 ----> insert in block
##### 3. In 3d array====> axis=1 ----> insert in row
##### 3. In 3d array====> axis=2 ----> insert in column

In [190]:
arr_insert_1d=np.insert(arr_1d, 4, 100 , axis=0)
print(arr_insert_1d, "\n")

arr_insert_2d=np.insert(arr_2d, 1, [78,89,90], axis=0)
print(arr_insert_2d,"\n")
arr_insert_2d1=np.insert(arr_2d, 1, [78], axis=1)
print(arr_insert_2d1,"\n\n\n")

arr_insert_3d=np.insert(arr_3d, 1, [[[12,23,45],[56,67,78],[89,90,10]]], axis=0)
print("inserting block: \n",arr_insert_3d,"\n\n")
arr_insert_3d1=np.insert(arr_3d, 1, [1,2,3], axis=1)
print("inserting row: \n",arr_insert_3d1,"\n\n")
arr_insert_3d2=np.insert(arr_3d, 1, [[101,202,303],[102,203,304]], axis=2)
print("inserting column: \n",arr_insert_3d2)

[  1   2   3   4 100   5   6   7   8   9] 

[[ 1  2  3]
 [78 89 90]
 [ 4  5  6]
 [ 7  8  9]] 

[[ 1 78  2  3]
 [ 4 78  5  6]
 [ 7 78  8  9]] 



inserting block: 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[12 23 45]
  [56 67 78]
  [89 90 10]]

 [[11 22 33]
  [44 55 66]
  [77 88 99]]] 


inserting row: 
 [[[ 1  2  3]
  [ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 22 33]
  [ 1  2  3]
  [44 55 66]
  [77 88 99]]] 


inserting column: 
 [[[  1 101   2   3]
  [  4 202   5   6]
  [  7 303   8   9]]

 [[ 11 102  22  33]
  [ 44 203  55  66]
  [ 77 304  88  99]]]


## 2. Appending - adding in last -- np.append(array, value, axis)

In [191]:
arr_append_1d=np.append(arr_1d, [2222], axis=0)
print("Appending in 1d is: \n",arr_append_1d,"\n\n\n")


arr_append_2d=np.append(arr_2d, [[2222,3333,4444]], axis=0)
print("Appending in 2d row is: \n",arr_append_2d,"\n\n\n")
arr_append_2d1=np.append(arr_2d, [[2323],[3434],[4242]], axis=1)
print("Appending in 2d col is: \n",arr_append_2d1,"\n\n\n")



arr_append_3d=np.append(arr_3d, [[[10,20,30],[40,50,60],[70,80,90]]], axis=0)
print("Appending in 3d block is: \n",arr_append_3d,"\n\n\n")

arr_append_3d1=np.append(arr_3d, [[[2323,3434,4545]],[[21,31,41]]], axis=1)
print("Appending in 3d row is: \n",arr_append_3d1,"\n\n\n")

arr_append_3d2=np.append(arr_3d, [[[2222],[3333],[4444]],[[2222],[3333],[4444]]], axis=2)
print("Appending in 3d col is: \n",arr_append_3d2,"\n\n\n")


Appending in 1d is: 
 [   1    2    3    4    5    6    7    8    9 2222] 



Appending in 2d row is: 
 [[   1    2    3]
 [   4    5    6]
 [   7    8    9]
 [2222 3333 4444]] 



Appending in 2d col is: 
 [[   1    2    3 2323]
 [   4    5    6 3434]
 [   7    8    9 4242]] 



Appending in 3d block is: 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 22 33]
  [44 55 66]
  [77 88 99]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]] 



Appending in 3d row is: 
 [[[   1    2    3]
  [   4    5    6]
  [   7    8    9]
  [2323 3434 4545]]

 [[  11   22   33]
  [  44   55   66]
  [  77   88   99]
  [  21   31   41]]] 



Appending in 3d col is: 
 [[[   1    2    3 2222]
  [   4    5    6 3333]
  [   7    8    9 4444]]

 [[  11   22   33 2222]
  [  44   55   66 3333]
  [  77   88   99 4444]]] 





## 3. Concatinate - joining two arrays -- np.concatinate((array1, array2), axis)

In [192]:
arr2_1d=np.array([900,800,700])
concatinate_1d=np.concatenate((arr_1d, arr2_1d) , axis=0)
print("concatinate 1d array: ",concatinate_1d,"\n\n\n")

arr2_2d=np.array([[15,25,95],[35,45,85],[55,65,75]])
concatinate_2d_row=np.concatenate((arr_2d, arr2_2d), axis=0)
print("concatinate 2d array row: \n",concatinate_2d_row,"\n\n\n")

arr2_2d1=np.array([[15],[35],[55]])
concatinate_2d_col=np.concatenate((arr_2d, arr2_2d1), axis=1)
print("concatinate 2d array col: \n",concatinate_2d_col,"\n\n\n")



arr2_3d=np.array([[[1212,2323,3434],[3434,4545,5656],[6767,7878,8989]]])
concatinate_3d_block=np.concatenate((arr_3d, arr2_3d), axis=0)
print("concatinate 3d array block: \n",concatinate_3d_block,"\n\n\n")


arr2_3d1=np.array([[[1,3,4]],[[2,5,6]]])
concatinate_3d_row=np.concatenate((arr_3d, arr2_3d1), axis=1)
print("concatinate 3d array row: \n",concatinate_3d_row,"\n\n\n")


arr2_3d2=np.array([[[1],[2],[3]],[[4],[5],[6]]])
concatinate_3d_col=np.concatenate((arr_3d, arr2_3d2), axis=2)
print("concatinate 3d array block: \n",concatinate_3d_col,"\n\n\n")


concatinate 1d array:  [  1   2   3   4   5   6   7   8   9 900 800 700] 



concatinate 2d array row: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [15 25 95]
 [35 45 85]
 [55 65 75]] 



concatinate 2d array col: 
 [[ 1  2  3 15]
 [ 4  5  6 35]
 [ 7  8  9 55]] 



concatinate 3d array block: 
 [[[   1    2    3]
  [   4    5    6]
  [   7    8    9]]

 [[  11   22   33]
  [  44   55   66]
  [  77   88   99]]

 [[1212 2323 3434]
  [3434 4545 5656]
  [6767 7878 8989]]] 



concatinate 3d array row: 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 1  3  4]]

 [[11 22 33]
  [44 55 66]
  [77 88 99]
  [ 2  5  6]]] 



concatinate 3d array block: 
 [[[ 1  2  3  1]
  [ 4  5  6  2]
  [ 7  8  9  3]]

 [[11 22 33  4]
  [44 55 66  5]
  [77 88 99  6]]] 





## 4. Removing / Deleting : np.delete(array, index, axis)

 #### 1. 1d = np.delete(array, index, axis=0)

 #### 2. 2d = np.delete(array, row_index, axis=0)
 #### 2. 2d = np.delete(array, col_index, axis=1)

 #### 3. 3d = np.delete(array, block_index, axis=0)
 #### 3. 3d = np.delete(array, row_index, axis=1)
 #### 3. 3d = np.delete(array, col_index, axis=2)

In [193]:
arr_delete_1d=np.delete(arr_1d, 2, axis=0)
print(arr_delete_1d,"\n\n\n")

arr_delete_2d=np.delete(arr2_2d, 1, axis=0)
print("deleted row: \n",arr_delete_2d,"\n\n")
arr_delete_2d=np.delete(arr2_2d, 1, axis=1)
print("deleted column: \n",arr_delete_2d)

arr_delete_3d=np.delete(arr_3d, 1, axis=0)
print("deleted array block:\n",arr_delete_3d,"\n\n")
arr_delete_3d=np.delete(arr_3d, 1, axis=1)
print("deleted array block:\n",arr_delete_3d,"\n\n")
arr_delete_3d=np.delete(arr_3d, 1, axis=2)
print("deleted array block:\n",arr_delete_3d,"\n\n")

[1 2 4 5 6 7 8 9] 



deleted row: 
 [[15 25 95]
 [55 65 75]] 


deleted column: 
 [[15 95]
 [35 85]
 [55 75]]
deleted array block:
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]] 


deleted array block:
 [[[ 1  2  3]
  [ 7  8  9]]

 [[11 22 33]
  [77 88 99]]] 


deleted array block:
 [[[ 1  3]
  [ 4  6]
  [ 7  9]]

 [[11 33]
  [44 66]
  [77 99]]] 




## 5. Stacking - np.vstack(), np.hstack() 

#### 1. nd_vstack = np.vstack((arr1, arr2)) ---> stacking vertically
#### 2. nd_vstack = np.hstack((arr1, arr2)) ---> stacking horizontally

In [194]:
arr_1d_stacking=np.array([1,2,3])
arr_1d_stacking2=np.array([4,5,6])

arr_vstack_1d=np.vstack((arr_1d_stacking, arr_1d_stacking2))
print(arr_vstack_1d)
arr_hstack_1d=np.hstack((arr_1d_stacking, arr_1d_stacking2))
print(arr_hstack_1d)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [195]:
arr_2d_stacking=np.array([[1,2],[3,4],[5,6],[7,8]])
arr_2d_stacking2=np.array([[11,22],[33,44],[55,66],[77,88]])

arr_2d_vstack=np.vstack((arr_2d_stacking,arr_2d_stacking2))
print(arr_2d_vstack,"\n\n\n")
arr_2d_hstack=np.hstack((arr_2d_stacking,arr_2d_stacking2))
print(arr_2d_hstack)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [11 22]
 [33 44]
 [55 66]
 [77 88]] 



[[ 1  2 11 22]
 [ 3  4 33 44]
 [ 5  6 55 66]
 [ 7  8 77 88]]


In [196]:
arr_3d_stacking = np.array([
                            [[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9]],

                            [[11, 12, 13],
                            [14, 15, 16],
                            [17, 18, 19]]
                        ])
arr_3d_stacking2 = np.array([
                            [[12, 23, 34],
                            [45, 56, 67],
                            [78, 89, 91]],

                            [[112, 123, 134],
                            [145, 156, 167],
                            [178, 189, 191]]
                        ])
arr_3d_vstack=np.vstack((arr_3d_stacking,arr_3d_stacking2))
print(arr_3d_vstack,"\n\n\n")
arr_3d_hstack=np.hstack((arr_3d_stacking,arr_3d_stacking2))
print(arr_3d_hstack,"\n\n\n")


[[[  1   2   3]
  [  4   5   6]
  [  7   8   9]]

 [[ 11  12  13]
  [ 14  15  16]
  [ 17  18  19]]

 [[ 12  23  34]
  [ 45  56  67]
  [ 78  89  91]]

 [[112 123 134]
  [145 156 167]
  [178 189 191]]] 



[[[  1   2   3]
  [  4   5   6]
  [  7   8   9]
  [ 12  23  34]
  [ 45  56  67]
  [ 78  89  91]]

 [[ 11  12  13]
  [ 14  15  16]
  [ 17  18  19]
  [112 123 134]
  [145 156 167]
  [178 189 191]]] 





## 6. Splitting - np.split(array, parts), np.hsplit(), np.vsplit()

#### 1. 1d ===> np.split(array, parts) ----> only if number of parts are valid

#### 2. 2d ===> np.split(array, parts, axis) ----> axis=0 ie row wise split(hsplit), axis=1 ie col wise split(vsplit)

#### 3. 3d ===> np.split(array, parts, axis) ----> axis=0 ie blockwise split, axis=1 ie row split, axis=2 ie col split(dsplit())

In [197]:
arr_split_1d=np.split(arr_1d,3) 
print(arr_split_1d)

arr_split_2d_row=np.hsplit(arr_2d,3)
print(arr_split_2d_row)
arr_split_2d_col=np.vsplit(arr_2d,3)
print(arr_split_2d_col)

arr_split_3d_col=np.dsplit(arr_3d,3)
print("\n\n\n",arr_split_3d_col)
arr_split_3d_row=np.split(arr_3d,3, axis=1)
print("\n\n\n",arr_split_3d_row)
arr_split_3d_block=np.split(arr_3d,2, axis=0)
print("\n\n\n",arr_split_3d_block)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]



 [array([[[ 1],
        [ 4],
        [ 7]],

       [[11],
        [44],
        [77]]]), array([[[ 2],
        [ 5],
        [ 8]],

       [[22],
        [55],
        [88]]]), array([[[ 3],
        [ 6],
        [ 9]],

       [[33],
        [66],
        [99]]])]



 [array([[[ 1,  2,  3]],

       [[11, 22, 33]]]), array([[[ 4,  5,  6]],

       [[44, 55, 66]]]), array([[[ 7,  8,  9]],

       [[77, 88, 99]]])]



 [array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]]), array([[[11, 22, 33],
        [44, 55, 66],
        [77, 88, 99]]])]
