# Indexing and Slicing in numpy arrays

## # Getting started - importing

In [2]:
import numpy as np

---
---
---
## 1. Indexing : (accessing a single element)
Indexing is the way you access individual elements (or groups of elements) from data structures like arrays, lists, or strings.

same as python indexing- ie from zero to end, and also negative indexng possible

for 1d- arry[index]
for 2d- arry[row,column]
for 3d- arry[block,row,column]

In [3]:
arr_indexing_1d=np.array([1,2,3,4,5,6,7,8,9])
arr_indexing_2d=np.array([[1,2,3,4],
                          [5,6,7,8],
                          [9,10,11,12]])
arr_indexing_3d=np.array([[[1,2,3],
                           [4,5,6]],
                          [[11,22,33],
                           [44,55,66]],
                          [[12,23,34],
                           [45,56,67]]])
print(arr_indexing_1d[3])
print(arr_indexing_1d[-3])

print(arr_indexing_2d[2,1])
print(arr_indexing_2d[-2,1])

print(arr_indexing_3d[1,1,0])
print(arr_indexing_3d[-1,1,-1])

4
7
10
6
44
67


## 2. Slicing : (accessing a range of elements)
Slicing is used to access a range of elements from arrays, lists, strings, etc.
Instead of picking one value (like indexing), slicing gives you a subset.

array[start:stop:step] ->>{stop not included}

#### 1. 1d array= array[start:stop:step]
#### 2. 2d array= array[row_start : row_stop : row_end , col_start : col_stop : col_step]
#### 3. 2d array= array[block_start : block_end : block_step, row_start   : row_end   : row_step, col_start   : col_end   : col_step]

In [4]:
print(arr_indexing_1d[2:5:2])
print(arr_indexing_1d[::-1])
print(arr_indexing_1d[::3])

print("\n")

print(arr_indexing_2d[1:: , ::2])
print(arr_indexing_2d[: , :])
print(arr_indexing_2d[:1 , 1:])

print("\n")

print(arr_indexing_3d[1: , : , :2])

[3 5]
[9 8 7 6 5 4 3 2 1]
[1 4 7]


[[ 5  7]
 [ 9 11]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3 4]]


[[[11 22]
  [44 55]]

 [[12 23]
  [45 56]]]


## 3. Fancy Indexing : (selecting multiple elements at once )---> arr[[index1, index2, index3]]
Fancy Indexing means accessing array elements using lists or arrays of indices, instead of plain slices.

Think of it like:
"Give me elements at these exact positions!"



(i) 1d fancy indexing: ----> array( [list of indexes] )

In [5]:
print(arr_indexing_1d[[0,2,3]])


[1 3 4]


(ii) 2d fancy indexing: ----> array( [list of rows] , [list to cols] )======> row = col single element respectively

------> array( [rows only] ) ====> select particular rows

------> array( [ : , [columns] ] ) =====> selecting rows by slicing and then specific columns by fancy indexing

In [6]:
print(arr_indexing_2d[[1,2],[1,3]])

[ 6 12]


(iii) 3d fancy indexing ----> array( [block list] , [rows list] , [columns list] )

In [7]:
print(arr_indexing_3d[[1] , [1] , [1]])

[55]


## 4. Boolean Masking & filtering - 
Boolean Masking ===> The process of creating a boolean array (True/False) based on a condition (eg. mask = arr > 10 → [False, True, True])

filtering ===> The act of using the boolean mask to extract matching elements from the array  (eg. arr[mask] → [20, 30])


In [8]:
print(arr_indexing_1d[arr_indexing_1d>2]) # filtering + boolean masking


print(arr_indexing_1d>=4) # boolean masking
print(arr_indexing_1d[arr_indexing_1d>=4]) # filtering

print(arr_indexing_2d[arr_indexing_2d>=7])

print(arr_indexing_3d[arr_indexing_3d>=33])

[3 4 5 6 7 8 9]
[False False False  True  True  True  True  True  True]
[4 5 6 7 8 9]
[ 7  8  9 10 11 12]
[33 44 55 66 34 45 56 67]


## 5. Reshaping And Manupulating array :-

Reshaping means changing the shape (dimensions/structure) of a NumPy array without changing its data.

Manipulation includes reshaping, flattening, transposing, adding/removing dimensions, and more — to prepare data for analysis, processing, or modeling.

#### 1. Array.reshape(dimensions) ---> return a View (ie changing it will change orignal)........(.rshape() only work if the dimensions matches)

for conversion into 1 d array:
#### 2. Array.ravel(dimensions) ---> return a View (ie changing it will change orignal)
#### 3. Array.flatten(dimensions) ---> return a Copy (ie changing it will not change orignal)

In [12]:
arr_reshaped=arr_indexing_1d.reshape(3,3)
print(arr_reshaped ,"\n")

arr_ravel=arr_indexing_2d.ravel()
print(arr_ravel, "\n")

arr_flatten=arr_indexing_3d.flatten()
print(arr_flatten)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[ 1  2  3  4  5  6  7  8  9 10 11 12] 

[ 1  2  3  4  5  6 11 22 33 44 55 66 12 23 34 45 56 67]
