# Broadcasting and Vectorization :- 

### # Broadcasting = Broadcasting is a powerful feature that allows NumPy to perform operations between arrays of different shapes without writing loops. ===> arrays of different sizes can be operated together

### # Vectorization = Vectorization is the process of performing operations on entire arrays (vectors, matrices, etc.) without using explicit loops, by using optimized low-level implementations. ===> if you want to operate each element of a array

In [1]:
import numpy as np

## # Broadcasting :-

In [10]:
#1d scalar broadcasting :- (do operations bw arrays of different sizes)
arr_1d=np.array([1,2,3])
b=[20]

print(arr_1d + b)
print(arr_1d - b)
print(arr_1d * b)
print(arr_1d / b)

[21 22 23]
[-19 -18 -17]
[20 40 60]
[0.05 0.1  0.15]


In [11]:
#2d scalar broadcasting:-
arr_2d=np.array([[1,2],[2,3]])
c=11

print(arr_2d + b)
print(arr_2d - b)
print(arr_2d * b)
print(arr_2d / b)

[[21 22]
 [22 23]]
[[-19 -18]
 [-18 -17]]
[[20 40]
 [40 60]]
[[0.05 0.1 ]
 [0.1  0.15]]


In [13]:
#3d scalar broadcasting :-
arr_3d=np.array([[[1,2,3],[2,3,4],[5,6,7]],[[11,22,33],[44,55,66],[77,88,99]]])
d=12

print(arr_3d + b)
print(arr_3d - b)
print(arr_3d * b)
print(arr_3d / b)

[[[ 21  22  23]
  [ 22  23  24]
  [ 25  26  27]]

 [[ 31  42  53]
  [ 64  75  86]
  [ 97 108 119]]]
[[[-19 -18 -17]
  [-18 -17 -16]
  [-15 -14 -13]]

 [[ -9   2  13]
  [ 24  35  46]
  [ 57  68  79]]]
[[[  20   40   60]
  [  40   60   80]
  [ 100  120  140]]

 [[ 220  440  660]
  [ 880 1100 1320]
  [1540 1760 1980]]]
[[[0.05 0.1  0.15]
  [0.1  0.15 0.2 ]
  [0.25 0.3  0.35]]

 [[0.55 1.1  1.65]
  [2.2  2.75 3.3 ]
  [3.85 4.4  4.95]]]


In [19]:
#2d with 1d broadcasting :-
arr_1d_1=np.array([1,2])
arr_2d_1=np.array([[1,2],[4,5]])

print(arr_1d_1+arr_2d_1)

[[2 4]
 [5 7]]


In [17]:
#3d with 1d broadcasting :-
arr_1d_2=np.array([1,2,3])
arr_3d_2=np.array([[[1,2,3],[4,5,6]],[[11,22,33],[44,55,66]]])

print(arr_1d_2+arr_3d_2)

[[[ 2  4  6]
  [ 5  7  9]]

 [[12 24 36]
  [45 57 69]]]


In [18]:
#3d with 2d broadcasting :-
arr_3d_3 = np.array([
    [[1, 2, 3], 
     [4, 5, 6], 
     [7, 8, 9]],

    [[10, 11, 12], 
     [13, 14, 15], 
     [16, 17, 18]]
])

arr_2d_3 = np.array([
    [100, 200, 300],
    [400, 500, 600],
    [700, 800, 900]
])


print(arr_3d_3+arr_2d_3)

[[[101 202 303]
  [404 505 606]
  [707 808 909]]

 [[110 211 312]
  [413 514 615]
  [716 817 918]]]


## # Vectorization
---> performing a same operation on all elements at once without using loops:-

In [20]:
#eg1:-
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr)

square_arr= arr**2
print(square_arr)

[1 2 3 4 5 6 7 8 9]
[ 1  4  9 16 25 36 49 64 81]


In [27]:
arr1 = np.array([1, 4, 9, 16])

arr2=np.sqrt(arr1)
print(arr2)

arr3= np.log(arr1)
print(arr3)

arr4= np.exp(arr1)
print(arr4)

arr5= np.sin(arr1)
print(arr5)


[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332]


In [32]:
arr11=np.array([11,22,33])
arr22=np.array([44,55,66])

arr33=arr11+arr22

arr44=arr11*33

arr55=arr11**3

arr66=arr11*arr22

print(arr33)
print(arr44)
print(arr55)
print(arr66)

[55 77 99]
[ 363  726 1089]
[ 1331 10648 35937]
[ 484 1210 2178]
