# Missing Values Handling :-
np.nan---> not a number --> to write nan values


np.isnan(array)== detect a missing value --> return a boolean array (T/F)

In [1]:
import numpy as np 

In [4]:
arr=np.array([1,2,3,np.nan,5,6,7,8,9])

print(np.isnan(arr))

[False False False  True False False False False False]


### # Removing nan values --- array[~np.isnan(arr)]

In [10]:
arr1=np.array([1,2,3, np.nan, 5,np.nan,7, np.nan,9])

removed=arr1[~np.isnan(arr1)]
print(removed)

[1. 2. 3. 5. 7. 9.]


### # Replacing missing values with --- np.where[np.isnan(arr), value, arr]

In [24]:
arr2=np.array([1,2,np.nan, 4,5, np.nan, 6,7])
replaced=np.where(np.isnan(arr2), 123, arr2)
print(replaced)
replaced=np.where(np.isnan(arr2), np.nanmean(arr2), arr2)
print(replaced)
replaced=np.where(np.isnan(arr2), np.nanmax(arr2), arr2)
print(replaced)
replaced=np.where(np.isnan(arr2), np.nanmin(arr2), arr2)
print(replaced)
replaced=np.where(np.isnan(arr2), np.nansum(arr2),arr2)
print(replaced)

[  1.   2. 123.   4.   5. 123.   6.   7.]
[1.         2.         4.16666667 4.         5.         4.16666667
 6.         7.        ]
[1. 2. 7. 4. 5. 7. 6. 7.]
[1. 2. 1. 4. 5. 1. 6. 7.]
[ 1.  2. 25.  4.  5. 25.  6.  7.]


### # Replace with -----> np.nan_to_num(array, nan=value)  (default value =0)

In [26]:
print(np.nan_to_num(arr2, nan=55))

[ 1.  2. 55.  4.  5. 55.  6.  7.]


### # Checking infinity number (np.inf) ---> np.isinf(arr) ---> return a boolean array

In [28]:
arr3=np.array([1,2, np.inf, 4,5, -np.inf])
print(np.isinf(arr3))

[False False  True False False  True]


#### # replacing infinity number --> np.nan_to_nun(arr, posinf=value, neginf=-value)

In [31]:
remove_inf=np.nan_to_num(arr3, posinf=233, neginf=-22)
print(remove_inf)

[  1.   2. 233.   4.   5. -22.]
