# Array Modification

Getting started :-

In [112]:
import numpy as np

---> arrays are of fixed size, hence we have to modify array by making new array, ie orignal array remain same

In [113]:
arr_1d=np.array([1,2,3,4,5,6,7,8,9])
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_3d=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[11,22,33],[44,55,66],[77,88,99]]])

print(arr_1d ,"\n\n\n")
print(arr_2d, "\n\n\n\n\n")
print(arr_3d, "\n\n\n")

[1 2 3 4 5 6 7 8 9] 



[[1 2 3]
 [4 5 6]
 [7 8 9]] 





[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 22 33]
  [44 55 66]
  [77 88 99]]] 





### 1. Insert - np.insert(array, index, value, axis=NONE)

##### 1. In 1d array====> axis=0 default

##### 2. In 2d array====> axis=0 ----> insert in row
##### 2. In 2d array====> axis=1 ----> insert in column


##### 3. In 3d array====> axis=0 ----> insert in block
##### 3. In 3d array====> axis=1 ----> insert in row
##### 3. In 3d array====> axis=2 ----> insert in column

In [114]:
arr_insert_1d=np.insert(arr_1d, 4, 100 , axis=0)
print(arr_insert_1d, "\n")

arr_insert_2d=np.insert(arr_2d, 1, [78,89,90], axis=0)
print(arr_insert_2d,"\n")
arr_insert_2d1=np.insert(arr_2d, 1, [78], axis=1)
print(arr_insert_2d1,"\n\n\n")

arr_insert_3d=np.insert(arr_3d, 1, [[[12,23,45],[56,67,78],[89,90,10]]], axis=0)
print("inserting block: \n",arr_insert_3d,"\n\n")
arr_insert_3d1=np.insert(arr_3d, 1, [1,2,3], axis=1)
print("inserting row: \n",arr_insert_3d1,"\n\n")
arr_insert_3d2=np.insert(arr_3d, 1, [[101,202,303],[102,203,304]], axis=2)
print("inserting column: \n",arr_insert_3d2)

[  1   2   3   4 100   5   6   7   8   9] 

[[ 1  2  3]
 [78 89 90]
 [ 4  5  6]
 [ 7  8  9]] 

[[ 1 78  2  3]
 [ 4 78  5  6]
 [ 7 78  8  9]] 



inserting block: 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[12 23 45]
  [56 67 78]
  [89 90 10]]

 [[11 22 33]
  [44 55 66]
  [77 88 99]]] 


inserting row: 
 [[[ 1  2  3]
  [ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 22 33]
  [ 1  2  3]
  [44 55 66]
  [77 88 99]]] 


inserting column: 
 [[[  1 101   2   3]
  [  4 202   5   6]
  [  7 303   8   9]]

 [[ 11 102  22  33]
  [ 44 203  55  66]
  [ 77 304  88  99]]]


## 2. Appending - adding in last -- np.append(array, value, axis)

In [115]:
arr_append_1d=np.append(arr_1d, [2222], axis=0)
print("Appending in 1d is: \n",arr_append_1d,"\n\n\n")


arr_append_2d=np.append(arr_2d, [[2222,3333,4444]], axis=0)
print("Appending in 2d row is: \n",arr_append_2d,"\n\n\n")
arr_append_2d1=np.append(arr_2d, [[2323],[3434],[4242]], axis=1)
print("Appending in 2d col is: \n",arr_append_2d1,"\n\n\n")



arr_append_3d=np.append(arr_3d, [[[10,20,30],[40,50,60],[70,80,90]]], axis=0)
print("Appending in 3d block is: \n",arr_append_3d,"\n\n\n")

arr_append_3d1=np.append(arr_3d, [[[2323,3434,4545]],[[21,31,41]]], axis=1)
print("Appending in 3d row is: \n",arr_append_3d1,"\n\n\n")

arr_append_3d2=np.append(arr_3d, [[[2222],[3333],[4444]],[[2222],[3333],[4444]]], axis=2)
print("Appending in 3d col is: \n",arr_append_3d2,"\n\n\n")


Appending in 1d is: 
 [   1    2    3    4    5    6    7    8    9 2222] 



Appending in 2d row is: 
 [[   1    2    3]
 [   4    5    6]
 [   7    8    9]
 [2222 3333 4444]] 



Appending in 2d col is: 
 [[   1    2    3 2323]
 [   4    5    6 3434]
 [   7    8    9 4242]] 



Appending in 3d block is: 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 22 33]
  [44 55 66]
  [77 88 99]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]] 



Appending in 3d row is: 
 [[[   1    2    3]
  [   4    5    6]
  [   7    8    9]
  [2323 3434 4545]]

 [[  11   22   33]
  [  44   55   66]
  [  77   88   99]
  [  21   31   41]]] 



Appending in 3d col is: 
 [[[   1    2    3 2222]
  [   4    5    6 3333]
  [   7    8    9 4444]]

 [[  11   22   33 2222]
  [  44   55   66 3333]
  [  77   88   99 4444]]] 





## 3. Concatinate - joining two arrays -- np.concatinate((array1, array2), axis)

In [116]:
arr2_1d=np.array([900,800,700])
concatinate_1d=np.concatenate((arr_1d, arr2_1d) , axis=0)
print("concatinate 1d array: ",concatinate_1d,"\n\n\n")

arr2_2d=np.array([[15,25,95],[35,45,85],[55,65,75]])
concatinate_2d_row=np.concatenate((arr_2d, arr2_2d), axis=0)
print("concatinate 2d array row: \n",concatinate_2d_row,"\n\n\n")

arr2_2d1=np.array([[15],[35],[55]])
concatinate_2d_col=np.concatenate((arr_2d, arr2_2d1), axis=1)
print("concatinate 2d array col: \n",concatinate_2d_col,"\n\n\n")



arr2_3d=np.array([[[1212,2323,3434],[3434,4545,5656],[6767,7878,8989]]])
concatinate_3d_block=np.concatenate((arr_3d, arr2_3d), axis=0)
print("concatinate 3d array block: \n",concatinate_3d_block,"\n\n\n")


arr2_3d1=np.array([[[1,3,4]],[[2,5,6]]])
concatinate_3d_row=np.concatenate((arr_3d, arr2_3d1), axis=1)
print("concatinate 3d array row: \n",concatinate_3d_row,"\n\n\n")


arr2_3d2=np.array([[[1],[2],[3]],[[4],[5],[6]]])
concatinate_3d_col=np.concatenate((arr_3d, arr2_3d2), axis=2)
print("concatinate 3d array block: \n",concatinate_3d_col,"\n\n\n")


concatinate 1d array:  [  1   2   3   4   5   6   7   8   9 900 800 700] 



concatinate 2d array row: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [15 25 95]
 [35 45 85]
 [55 65 75]] 



concatinate 2d array col: 
 [[ 1  2  3 15]
 [ 4  5  6 35]
 [ 7  8  9 55]] 



concatinate 3d array block: 
 [[[   1    2    3]
  [   4    5    6]
  [   7    8    9]]

 [[  11   22   33]
  [  44   55   66]
  [  77   88   99]]

 [[1212 2323 3434]
  [3434 4545 5656]
  [6767 7878 8989]]] 



concatinate 3d array row: 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 1  3  4]]

 [[11 22 33]
  [44 55 66]
  [77 88 99]
  [ 2  5  6]]] 



concatinate 3d array block: 
 [[[ 1  2  3  1]
  [ 4  5  6  2]
  [ 7  8  9  3]]

 [[11 22 33  4]
  [44 55 66  5]
  [77 88 99  6]]] 



