# NumPy BASICS

## Getting started - import :-

In [60]:
import numpy as np

---
---
---
## 1. Knowing - shape,size,type of any array :-

(i) finding shape of an array - array.shape


In [61]:
d2_arr=np.array([[1,2,3,4,5], [8,9,0,3,2], [1,3,5,7,8]])
print(d2_arr.shape)

(3, 5)


(ii) finding size of array ie total number of elements in that array - array.size

In [62]:
print(d2_arr.size)

15


(iii) finding the number of dimensions - array.ndim

In [63]:
print(d2_arr.ndim)

2


(iv) checking datatype of array elements - array.dtype (int,float, or str etc)

In [64]:
d_arr=np.array([1,2.3,5.6])
print(d2_arr.dtype)
print(d_arr.dtype)

int64
float64


(v) changing data-type of array elements - array.astype(new_data_type)

In [65]:
print(d_arr.dtype)
int_d_arr=d_arr.astype(int)
print(int_d_arr.dtype)

print(d2_arr.dtype)
float_d2_arr=d2_arr.astype(float)
print(float_d2_arr.dtype)

float64
int64
int64
float64


## 2. Mathematical operations on Arrays (on all elements of arr - 1d 2d 3d all)

### operator ------------> syntax
##### 1. addition (+)-------> arry+ num  (eg = arr+5)
##### 2. subtraction(-)-----> arr - n
##### 3. multiplication(*)--> arr * n
##### 4. division(/)--------> arr / n
##### 5. exponential(**)----> arr ** n 
##### 6. floor division(//)-> arr //  n 
##### 7. modulus(%) --------> arr % n

In [66]:
arr1=np.array([10,20,30])

add_10=arr1+10
print(add_10)

sub_3=arr1-3
print(sub_3)

mul_30=arr1*30
print(mul_30)

div_5=arr1/5
print(div_5)

floor_div_2=arr1//2
print(floor_div_2)

modulus_7=arr1%7
print(modulus_7)

expo_4=arr1**4
print(expo_4)

[20 30 40]
[ 7 17 27]
[300 600 900]
[2. 4. 6.]
[ 5 10 15]
[3 6 2]
[ 10000 160000 810000]
