# This is file to install and run numpy (single # will be title 1)
---
For newline use three times \---
## for title 2 use \##
### for title 3 use \###
and this is plain tect

### #for installing write //pip install numpy
---
to import:


In [2]:
import numpy as np

# Arrays
---
## 1-d array

In [4]:
d1_array=np.array([1,2,3,4,5,6,7,8,9])
print(d1_array)

l1=[9,8,7,6,5,4,3,2,1]
d1_array2=np.array(l1)
print(d1_array2)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


## 2d arrays (matrix):


In [5]:
d2_array=np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(d2_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Multi-d arrays --- (imp for my field bruh)