# START: This is file to install and run numpy (single # will be title 1)
---
For newline use three times \---
## for title 2 use \##
### for title 3 use \###
and this is plain tect

---

### #for installing write //pip install numpy
---

{prerequisites- we have made a virtual environment where we installed this numpy so be aware, in simple ie outside this folder/environment you can access this numpy}

---

## to import:


In [18]:
import numpy as np

---
---
---
---
---

# Arrays
---
## 1-d array

In [19]:
d1_array=np.array([1,2,3,4,5,6,7,8,9])
print(d1_array)

l1=[9,8,7,6,5,4,3,2,1]
d1_array2=np.array(l1)
print(d1_array2)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


## 2d arrays (matrix):


In [20]:
d2_array=np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(d2_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Multi-d arrays --- (imp for my field bruh)

---
---

# for making arrays with default values:

---

## 1. for defauld values zero= np.zeros(shape)..........// shape= 1d 2d or etc== (3)-> 1d array of size 3.......(2,3) -> 2*3 matrix

implementation:


In [21]:
zero_arr=np.zeros((4))
print("1d zero array is:",zero_arr)
print("\n\n")
zero_array=np.zeros((3,5))
print("2d zero array:")
print(zero_array)

1d zero array is: [0. 0. 0. 0.]



2d zero array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## 2. For default values to be 1: (same syntax as zeros) == np.ones(shape)

In [22]:
one_arr=np.ones((6,2))
print(one_arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


## 3. for random default value == np.full(shape, element)

In [23]:
rand_arr=np.full((3,2),6)
print(rand_arr)

[[6 6]
 [6 6]
 [6 6]]


### # Printing sequence of numbers in arrays:
like range(start:stop:step) is in python here in numpy we have == arange(start,stop,step) = it returns the sequence in array form

In [24]:
seq_arr=np.arange(1,100,5)
print(seq_arr)

[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]


### # Making a identity matrix -> np.eye(shape) (no. rows = no. of col ......condn for this)
{
    An identity matrix is a square matrix (same number of rows and columns) with:

    All diagonal elements as 1

    All off-diagonal elements as 0
}

In [25]:
id_arr=np.eye(6)
print(id_arr)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
